services:
  practicas:
    build:
      context: ./
      dockerfile: Dockerfile
    image: python:3.12.4
    volumes:
      - ./output:/output
      - ./datos.csv:/datos.csv
    command: ["python", "/practicas/entrypoint.py"]
